version: "3"

services: 
  gympass-api-pg:
    image: "bitnami/postgresql"
    ports:
      - "8080:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABAES=gympass